apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: widgetfactory
  replicas: 1
  template:
    metadata:
      labels:
        app: widgetfactory
    spec:
      containers:
        - name: widgetfactory
          image: {{ .Values.widgetfactory.image }}
          ports:
            - containerPort: {{ .Values.widgetfactory.web.containerPort }}
              name: web
            - containerPort: {{ .Values.widgetfactory.metrics.containerPort }}
              name: metrics
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  key: mysql-root-password
                  name: {{ .Release.Name }}-mysql
            - name: MYSQL_HOST
              value: {{ .Release.Name}}-mysql
            - name: MYSQL_DB
              value: {{ .Release.Name}}
            - name: MYSQL_PORT
              value: "3306"