apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.widgetfactory.web.servicePort }}
      targetPort: {{ .Values.widgetfactory.web.containerPort }}
      name: web
    - port: {{ .Values.widgetfactory.metrics.servicePort }}
      targetPort: {{ .Values.widgetfactory.metrics.containerPort }}
      name: metrics
  type: {{ .Values.widgetfactory.serviceType }}