apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: widgetfactory
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: widget-factory
      component: web-server
